### PR TITLE
[WIP] Added CHANGELOG.md, test-kitchen config, specs

### PR DESCRIPTION
**Pull request by mohitsethi**
This is still work in progress!

### CODE REVIEW

**Comment by mohitsethi** [comment]
@szelcsanyi do we need test for ruby 1.9.3?

**Comment by szelcsanyi** [comment]
I was thinking about backward compatibility (1.8 - 1.9.2 was dropped  https://github.com/chef/chef/commit/cf6ac3eb9b8b6de37972bb4fd07a03c57cdf33ea) but even 1.9.3 was dropped more than a year ago (https://github.com/chef/chef/commit/6305d684d55cf26e7250a33953345416ee847710). 
So we need only ruby version 2.0.0 and 2.1.5.

**Comment by mohitsethi** [comment]
:+1:

**Comment by szelcsanyi** [comment]
I like some of your changes but I cannot accept your whole pull request. I merged the custom user and group option. Next time, please make changes based on the latest version of this cookbook, make smaller PRs or squash them into one commit and do not rename the cookbook.

**Pull request closed without merging**
